language: ruby
before_install:
  - ./bcdice-js/ci/before_install.sh
install:
  - cd src && bundle install && cd ..
  - ./bcdice-js/ci/install.sh
script:
  - cd src
  - bundle exec rake
  - cd ..
  - ./bcdice-js/ci/script.sh
matrix:
  include:
    - rvm: 2.6
      env: TRAVIS_CI=1 BCDICE_JS=true
    - rvm: 2.5
      env: TRAVIS_CI=1 BCDICE_JS=true
    - rvm: 2.4
      env: TRAVIS_CI=1 BCDICE_JS=true
    - rvm: 2.3
      env: TRAVIS_CI=1 BCDICE_JS=true
    - rvm: 2.2.10
      env: TRAVIS_CI=1
    - rvm: 2.1.10
      env: TRAVIS_CI=1
    - rvm: 2.0.0
      env: TRAVIS_CI=1
    - rvm: 1.9.3
      env: TRAVIS_CI=1
    # - rvm: 1.8.7
    #   env: TRAVIS_CI=1
